version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
  wp:
    depends_on:
      - db
    image: wordpress-pixel-plugin-site:latest
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ../../build/official-facebook-pixel:/var/www/html/wp-content/plugins/official-facebook-pixel
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
volumes:
  db_data:
